version: 2
jobs:
  build:
    docker:
      - image: circleci/node:jessie-browsers
      - image: circleci/openjdk:8u131-jdk
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
    #  - run: javac test.py 
      - run: mvn clean test
     
      