version: 2
jobs:
  build:
    docker:
      #- image: circleci/python:latest
      - image: circleci/openjdk:8u131-jdk
 
   #Latest image of python environment
    steps:
      - checkout # Checks out the source code from rehmanuet's repo default directory
      - run: java -version  # Sample Command for Demonstration
      - run: ls
      - run:
          name: Download Selenium
          command: |
            curl -O https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
            curl -O https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
    #  - run: javac test.py 
      - run: mvn clean test
     
      - run: echo "Build Successfully"